### ISSUE TITLE
def of clear() function

### ISSUE THREAD

**Issue by Spheres-cu** [csq/subdivx-dl#1]
In the definition of clear () 

def clear():
    os.system('clr' if os.name == 'nt' else 'clear')

 for Windows  (os.name='nt')   should be

def clear():
    os.system('cls if os.name == 'nt' else 'clear')

Or 'clear ' if Windows  console  is powershell

**Comment by csq** [comment]
Solved, thank you

**Comment by Spheres-cu** [comment]
> Solved, thank you

thank you for this script, in another Issues other problem in Windows 😅 see ya !
