### ISSUE TITLE
Parameters fixing  for wget in Windows

### ISSUE THREAD

**Issue by Spheres-cu** [csq/subdivx-dl#2]
The problem comes with the parameters that are passed to Popen in Windows: `' >/dev/null 2>&1 ; echo $?' ` because `>/dev/null and ; echo $` only works in Linux and not in CMD or PowerShell, in any case it should be:` 2>&1 && echo $`for Windows but first you would need to choose which parameters to pass depending on the OS using os.name to detect it

**Comment by Spheres-cu** [comment]
An idea:
```
    arg_file_zip = ('.zip 2>&1 && echo $' if os.name == 'nt' else '.zip >/dev/null ; echo $?')
    arg_file_rar = ('.rar 2>&1 && echo $' if os.name == 'nt' else '.rar >/dev/null ; echo $?')
    stop = False
    while (stop is False):
        address = url[:20] + 'sub'+ str(NUMBER_OF_SERVER) + '/' + url[20:]

        cmd1 = 'wget -U "{}"'.format(userAgent['user-agent']) + ' -qcP "{}" {}'.format(location, address) + arg_file_zip
        cmd2 = 'wget -U "{}"'.format(userAgent['user-agent']) + ' -qcP "{}" {}'.format(location, address) + arg_file_rar
```
I tested it in Windows 10 22H2 and Zorin 17.1 and work ok

**Comment by csq** [comment]
I have added your code https://github.com/csq/subdivx-dl/commit/cb8e7634c9633bdeadc7c8312c11d02f0d061700 and also solved an issue with the number of download requests. In Windows, regardless of whether I downloaded in a single request, the remaining requests continued. It took me a while, but it should work correctly.

**Comment by Spheres-cu** [comment]
> I have added your code [cb8e763](https://github.com/csq/subdivx-dl/commit/cb8e7634c9633bdeadc7c8312c11d02f0d061700) and also solved an issue with the number of download requests. In Windows, regardless of whether I downloaded in a single request, the remaining requests continued. It took me a while, but it should work correctly.

Working fine in Windows
