### ISSUE TITLE
pathfile for subdivx-dl.log in Windows

### ISSUE THREAD

**Issue by Spheres-cu** [csq/subdivx-dl#3]
The pathfile define in helper.py work only for /tmp folder in Linux but in Windows is other path  for example: `C:\Users\<user>\AppData\Local\Temp`  and I m getting error without -v parameter.

I fixed it by  importing the module tempfile  and changing this:

`#pathfile ='/tmp/subdivx-dl.log'`
`pathfile = tempfile.gettempdir() + 'subdivx-dl.log'`

I do not know if  it work for Linux and Mac

**Comment by csq** [comment]
Fixed in commit #https://github.com/csq/subdivx-dl/commit/97763282c8d5cdbc78084b5487776b99fafa767e. Yes, it works on any platform because the tempfile module resolves by itself where to create temporary files or directories.
